import type { ProjectType } from './types.js';

export const PROJECT_TYPE_PLUGINS: Record<ProjectType, string[]> = {
  nextjs: [
    'javascript-typescript',
    'frontend-mobile-development',
    'backend-development',
    'api-scaffolding',
    'ui-design',
    'accessibility-compliance',
    'seo-technical-optimization',
    'unit-testing',
    'tdd-workflows',
    'performance-testing-review',
    'frontend-mobile-security',
    'application-performance',
    'code-refactoring',
    'git-pr-workflows',
  ],

  'react-spa': [
    'javascript-typescript',
    'frontend-mobile-development',
    'ui-design',
    'accessibility-compliance',
    'unit-testing',
    'tdd-workflows',
    'performance-testing-review',
    'frontend-mobile-security',
    'application-performance',
    'code-refactoring',
    'git-pr-workflows',
    'dependency-management',
  ],

  flutter: [
    'multi-platform-apps',
    'frontend-mobile-development',
    'ui-design',
    'accessibility-compliance',
    'unit-testing',
    'tdd-workflows',
    'frontend-mobile-security',
    'application-performance',
    'code-refactoring',
    'git-pr-workflows',
    'error-debugging',
  ],

  'serverless-python': [
    'python-development',
    'cloud-infrastructure',
    'api-scaffolding',
    'backend-api-security',
    'database-design',
    'database-migrations',
    'unit-testing',
    'tdd-workflows',
    'cicd-automation',
    'deployment-strategies',
    'error-diagnostics',
    'code-refactoring',
    'git-pr-workflows',
  ],

  'serverless-node': [
    'javascript-typescript',
    'cloud-infrastructure',
    'api-scaffolding',
    'backend-api-security',
    'backend-development',
    'database-design',
    'database-migrations',
    'unit-testing',
    'tdd-workflows',
    'cicd-automation',
    'deployment-strategies',
    'error-diagnostics',
    'git-pr-workflows',
  ],
};
